/**
 * Writes src/common/enums.ts from the enum blocks in prisma/schema.prisma.
 *
 * SQLite has no enum type, so the generated Drizzle schema types those columns
 * as text and the Prisma client no longer exports them. This keeps one copy of
 * the values, generated from the same schema, rather than each module spelling
 * its own out and drifting.
 *
 *   node tools/prisma-enums.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';

const schema = readFileSync('prisma/schema.prisma', 'utf8');
const header = `/**
 * The enums the Prisma client used to export.
 *
 * SQLite has no enum type, so the generated Drizzle schema types these columns
 * as plain text. The names and values here are copied from schema.prisma and
 * are what is actually stored, so validation (\`@IsEnum\`) and comparisons keep
 * working exactly as they did — this file replaces the \`@prisma/client\`
 * import, not the meaning behind it.
 *
 * Generated by tools/prisma-enums.mjs. Re-run it if the schema changes.
 */
`;

const out = [header];
for (const [, name, body] of schema.matchAll(/^enum\s+(\w+)\s*\{([^}]*)\}/gm)) {
  const values = body
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l && !l.startsWith('//') && !l.startsWith('@'))
    .map((l) => l.split(/\s+/)[0]);
  out.push(`export const ${name} = {`);
  for (const v of values) out.push(`  ${v}: '${v}',`);
  out.push('} as const;');
  out.push(`export type ${name} = (typeof ${name})[keyof typeof ${name}];`);
  out.push('');
}

writeFileSync('src/common/enums.ts', out.join('\n'));
console.log(`Wrote src/common/enums.ts`);
