/**
 * The enums the Prisma client used to export.
 *
 * SQLite has no enum type, so the generated Drizzle schema types these columns
 * as plain text. The names and values here are copied from schema.prisma and
 * are what is actually stored, so validation (`@IsEnum`) and comparisons keep
 * working exactly as they did — this file replaces the `@prisma/client`
 * import, not the meaning behind it.
 *
 * Generated by tools/prisma-enums.mjs. Re-run it if the schema changes.
 */

export const UserRole = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  SITE_ADMIN: 'SITE_ADMIN',
  WATCHMAN: 'WATCHMAN',
  SUPERVISOR: 'SUPERVISOR',
} as const;
export type UserRole = (typeof UserRole)[keyof typeof UserRole];

export const WorkerStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  EXITED: 'EXITED',
  SUSPENDED: 'SUSPENDED',
} as const;
export type WorkerStatus = (typeof WorkerStatus)[keyof typeof WorkerStatus];

export const DeviceStatus = {
  PENDING: 'PENDING',
  AUTHORIZED: 'AUTHORIZED',
  REVOKED: 'REVOKED',
} as const;
export type DeviceStatus = (typeof DeviceStatus)[keyof typeof DeviceStatus];

export const SessionState = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  AUTO_CLOSED: 'AUTO_CLOSED',
  VOID: 'VOID',
} as const;
export type SessionState = (typeof SessionState)[keyof typeof SessionState];

export const TapType = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
} as const;
export type TapType = (typeof TapType)[keyof typeof TapType];

export const TapSource = {
  NFC_UID: 'NFC_UID',
  NFC_NDEF: 'NFC_NDEF',
  QR: 'QR',
  MANUAL: 'MANUAL',
} as const;
export type TapSource = (typeof TapSource)[keyof typeof TapSource];

export const VerificationMode = {
  MANUAL: 'MANUAL',
  AUTO: 'AUTO',
} as const;
export type VerificationMode = (typeof VerificationMode)[keyof typeof VerificationMode];

export const PhotoVerifyMode = {
  ALWAYS: 'ALWAYS',
  NEVER: 'NEVER',
  RANDOM: 'RANDOM',
} as const;
export type PhotoVerifyMode = (typeof PhotoVerifyMode)[keyof typeof PhotoVerifyMode];

export const CorrectionType = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  MISSING: 'MISSING',
  WRONG_SITE: 'WRONG_SITE',
} as const;
export type CorrectionType = (typeof CorrectionType)[keyof typeof CorrectionType];

export const CorrectionStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
} as const;
export type CorrectionStatus = (typeof CorrectionStatus)[keyof typeof CorrectionStatus];

export const CorrectionReason = {
  FORGOT_CARD: 'FORGOT_CARD',
  DEVICE_ISSUE: 'DEVICE_ISSUE',
  NETWORK_ISSUE: 'NETWORK_ISSUE',
  WRONG_SITE: 'WRONG_SITE',
  SUPERVISOR_MISTAKE: 'SUPERVISOR_MISTAKE',
  OTHER: 'OTHER',
} as const;
export type CorrectionReason = (typeof CorrectionReason)[keyof typeof CorrectionReason];

export const SyncEventStatus = {
  ACCEPTED: 'ACCEPTED',
  DUPLICATE: 'DUPLICATE',
  CONFLICT: 'CONFLICT',
  REJECTED: 'REJECTED',
} as const;
export type SyncEventStatus = (typeof SyncEventStatus)[keyof typeof SyncEventStatus];

export const ManualApprovalStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
} as const;
export type ManualApprovalStatus = (typeof ManualApprovalStatus)[keyof typeof ManualApprovalStatus];

export const CredentialKind = {
  NFC_UID: 'NFC_UID',
  QR: 'QR',
} as const;
export type CredentialKind = (typeof CredentialKind)[keyof typeof CredentialKind];

export const PersonCategory = {
  WORKER: 'WORKER',
  STAFF: 'STAFF',
  VISITOR: 'VISITOR',
} as const;
export type PersonCategory = (typeof PersonCategory)[keyof typeof PersonCategory];

export const PhotoKind = {
  PROFILE: 'PROFILE',
  AADHAAR_FRONT: 'AADHAAR_FRONT',
  AADHAAR_BACK: 'AADHAAR_BACK',
  ID_PROOF: 'ID_PROOF',
} as const;
export type PhotoKind = (typeof PhotoKind)[keyof typeof PhotoKind];

export const SafetyMetric = {
  DAILY_MANPOWER: 'DAILY_MANPOWER',
  TOTAL_MANPOWER: 'TOTAL_MANPOWER',
  TOTAL_SAFE_MAN_HOURS: 'TOTAL_SAFE_MAN_HOURS',
  LABOUR_INDUCTION: 'LABOUR_INDUCTION',
  TOOLBOX_TALK: 'TOOLBOX_TALK',
  WORK_PERMIT: 'WORK_PERMIT',
  UNSAFE_ACTS: 'UNSAFE_ACTS',
  UNSAFE_CONDITIONS: 'UNSAFE_CONDITIONS',
  UNSAFE_ACTS_CLOSED: 'UNSAFE_ACTS_CLOSED',
  UNSAFE_CONDITIONS_CLOSED: 'UNSAFE_CONDITIONS_CLOSED',
  SAFETY_OBSERVATION: 'SAFETY_OBSERVATION',
  SAFETY_OBSERVATION_CLOSED: 'SAFETY_OBSERVATION_CLOSED',
  NEAR_MISS: 'NEAR_MISS',
  FIRST_AID: 'FIRST_AID',
  MEDICAL_TREATMENT_CASE: 'MEDICAL_TREATMENT_CASE',
  LOST_TIME_INJURY: 'LOST_TIME_INJURY',
  SAFETY_INSPECTION: 'SAFETY_INSPECTION',
  WASTE_DISPOSAL: 'WASTE_DISPOSAL',
  VISITOR_INDUCTION: 'VISITOR_INDUCTION',
  SAFETY_AUDIT: 'SAFETY_AUDIT',
  TRAINING: 'TRAINING',
} as const;
export type SafetyMetric = (typeof SafetyMetric)[keyof typeof SafetyMetric];
